name: 图书馆签到

on:
  schedule:
    - cron: "30 23 * * *"
    - cron: "00 00 * * *"
    - cron: "30 00 * * *"
    - cron: "00 01 * * *"
    - cron: "00 05 * * *"
    - cron: "00 06 * * *"
    - cron: "00 10 * * *"
    - cron: "00 11 * * *"
  workflow_dispatch:
jobs:
  record:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: pip install -r GZHU_LibraryAutoReserve_sign/requirements.txt
      - name: Run python
        run: python GZHU_LibraryAutoReserve_sign/sign.py



      

