name: Daily job

on:
  schedule:
    - cron: "20 1 * * *"

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
  
    - name: Run Python script
      run: python 780-1500.py
    - name: Run Python script
      run: python 嘉蔚.py
    - name: Run Python script
      run: python 838-2000.py
