name: Daily job

于:
  schedule:
    - cron: "21 22 * * *"
  workflow_dispatch:

jobs:


  jiawei:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
  
    - name: Run Python script
      run: python 嘉蔚.py

  cha1162:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
  
    - name: Run Python script
      run: python 差1162.py
  like:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
  
    - name: Run Python script
      run: python 李可767-2000.py

  hexiao:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
  
    - name: Run Python script
      run: python 何啸.py
  wangxi:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
  
    - name: Run Python script
      run: python 王曦.py

  zhangmingdong:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
  
    - name: Run Python script
      run: python 张明东考试1500.py
      

