name: 图书馆预约签到

on:
  schedule:
    - cron: '35 15 * * *'
  workflow_dispatch:
  
jobs:
  booking:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: pip install -r GZHU_LibraryAutoReserve_sign/requirements.txt
      - name: Run python
        run: python GZHU_LibraryAutoReserve_sign/reserve.py


